version: '3.8'

services:
  # Flask Authentication Service
  auth-service:
    build: ./flask-user-system
    container_name: flask-auth
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PARENT_DOMAIN=localhost
    volumes:
      - ./flask-user-system/data:/app/data
    networks:
      - chat-network

  # FastAPI Chat Interface Service  
  chat-service:
    build: ./mad-scientist
    container_name: fastapi-chat
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:5000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - auth-service
    networks:
      - chat-network

  # Phoenix API Gateway Service
  phoenix-gateway:
    build: ./phoenix_gateway
    container_name: phoenix-gateway
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=prod
      - SECRET_KEY_BASE=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - AUTH_SERVICE_URL=http://auth-service:5000
      - CHAT_SERVICE_URL=http://chat-service:8000
      - DATABASE_URL=ecto://postgres:postgres@postgres:5432/phoenix_gateway_prod
    depends_on:
      - auth-service
      - chat-service
      - postgres
    networks:
      - chat-network

  # PostgreSQL Database for Phoenix
  postgres:
    image: postgres:15-alpine
    container_name: phoenix-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=phoenix_gateway_prod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - chat-service
      - phoenix-gateway
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  postgres_data:
