version: '3.8'

services:
  mad-scientist:
    build: .
    ports:
      - "8080:8000"  # Map local port 8080 to container port 8000
    volumes:
      - ./src:/app/src
      - ./local_dev.py:/app/local_dev.py
      - ./requirements.txt:/app/requirements.txt
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    restart: unless-stopped
