version: '3.8'

services:
  mad-scientist:
    build: .
    ports:
      - "8787:8787"
    volumes:
      - ./src:/app/src
      - ./wrangler.toml:/app/wrangler.toml
      - ./requirements.txt:/app/requirements.txt
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
    restart: unless-stopped
