version: '3.8'

services:
  # Flask Authentication Service
  auth-service:
    build: ./flask-user-system
    container_name: flask-auth
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PARENT_DOMAIN=localhost
    volumes:
      - ./flask-user-system/data:/app/data
    networks:
      - chat-network

  # FastAPI Chat Interface Service  
  chat-service:
    build: .
    container_name: fastapi-chat
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:5000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - auth-service
    networks:
      - chat-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - chat-service
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
